---

docker_autotest_templates:
    - src: "{{ custom_subtests_ini_j2 | default('subtests.ini.j2') }}"
      dest: "{{ autotest_docker_path }}/config_custom/subtests.ini"
    - src: "{{ custom_control_ini_j2 | default('control.ini.j2') }}"
      dest: "{{ autotest_docker_path }}/config_custom/control.ini"

docker_autotest:
    # FIXME: This should be using the fedora image, but it's missing python2
    # so a build_url should point at a dockerfile that takes care of this.
    # For now, just use the CentOS image and pretend any userspace/kernel mismatch
    # problems don't exist.
    test_image:
        host:
        user:
        name:
        tag:
        build_url:
    preserve_fqins: []
    preserve_cnames: []
    execute: true
    enable_bugzilla: true
