---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

dependencies:
    - common
    - role: kommandir_discovered 
      # Only _before_ job.xn runs, after would be too late :D
      when: not job_xn_done
    # Before and after job.xn is done
    - role: inventory_updated
      inventory_hostnames:
        - kommandir
