---

# Ensure slave is in the right groups
- include: localhost.yml

# creates peons
- hosts: openstack
  any_errors_fatal: true
  vars_files:
    # These can be overidden on command-line
    - vars/peon_defaults.yml
    - vars/peons.yml
  roles:
    - openstack

- include: peons.yml

- hosts: autotested:&{{ adept_job }}
  any_errors_fatal: true
  roles:
    - role: autotested
      when: docker_autotest is defined

- hosts: peons:&{{ adept_job }}
  roles:
    # Must be very last role, determines some behaviors in run transition
    - touchstone
