---

# Ensure slave is in the right groups
- include: localhost.yml

# creates peons
- hosts: openstack
  any_errors_fatal: true
  vars_files:
    # These can be overidden on command-line
    - vars/peon_defaults.yml
    - vars/peons.yml
  roles:
    - openstack

- include: peons.yml

# TODO actually do the setup steps here instead of in run
# - hosts: autotested:&{{ adept_job }}
#   any_errors_fatal: true
#   roles:
#     - role: autotested
