---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

# Always create/locate kommandir first (it may have gone away)
- include: kommandir.yml

# Only needed for remote kommandirs, and only _after_ 
# exekutir.xn's call to kommandir's job.xn
# (i.e. this playbook is called _twice_)
- hosts: exekutir:!nocloud
  # Ensure exclusive lock is released, even on role failure
  force_handlers: True
  roles:
    - role: exekutir_lock
      # define lock-type variable contents just for this role
      lock_type: "exclusive"
    # This might destroy the kommandir, but doesn't have to.
    - kommandir_destroyed

# No reason for this to execute under a lock or if adept_debug enabled
- hosts: exekutir
  roles:
    - role: exekutir_workspace_cleanup
      # adept_debug only defined by ansible command-line
      when: not adept_debug
