---

- debug: var=docker_autotest.timeout
  when: docker_autotest.timeout is defined

- name: Control timeout set
  lineinfile:
    backrefs: true
    dest: "{{ autotest_docker_path }}/control"
    follow: True
    line: "\\1 {{ docker_autotest_timeout }}"
    regexp: "^(TIMEOUT\\s*=\\s*).*$"
  when: docker_autotest_timeout is defined
