---

# Directory containing 'autotest' and 'autotest-docker' repos.
docker_autotest_cache_dir: "{{ workspace }}/cache/"

# Remote directory where Autotest will be installed
autotest_dest_dir: "/var/lib/autotest"

# Timeout in seconds to rewrite into control-file, will be divided
# equally among all subtests.
docker_autotest_timeout: "{{ docker_autotest_timeout | default(3600) }}"

docker_autotest:

    # Many tests rely on a default image for testing. Specify
    # either _all_ components of the fully-qualified-image-name.
    # or no components to use defaults from docker autotest.
    test_image:
        name:
        tag:
        host:
        user:
        # Build this image from url, tagged as above name.
        # Leave empty to pull test image instead.
        build_url:

    # List of subtests to include, empty to use defaults
    # (runs _all_ specified by subthings, below).
    include: []

    # List of pre/intra/post/sub-tests to exclude,
    # empty for none.
    exclude:
        - example
        - subexample
        - pretest_example
        - intratest_example
        - posttest_example
        # Doesn't work on Atomic Host
        - docker_cli/build/git_path
        # Depends on storage sizes / docker-storage-setup
        - docker_cli/info
        # Possibly highly docker-version sensitive
        - docker_cli/negativeusage
        # Depends on external resources
        - docker_cli/run_volumes

    # List of pre/intra/post/sub-tests to run (in order),
    # empty to run everything.
    subthings: []

    # List of template arg dictionaries use, empty for none
    # e.g. - dest: "config_custom/tests.ini"
    #        src: "tests.ini.j2"
    templates:
        - src: "subtests.ini.j2"
          dest: "{{ autotest_docker_path }}/config_custom/subtests.ini"

    # List of fqins to protect from removal during all tests
    preserve_fqins: []

    # List of container names to protect from removal during all tests
    preserve_cnames: []

    # Set to false to disable executing autotest on this host
    execute: true

    # Enable or disable checking of bugzilla entries for tests to skip
    enable_bugzilla: true

    # The variables below allow flexibility to dynamicly determine
    # what docker repositories, container names and versions to
    # act upon.  More than likely they do not need to be modified
    # from default values unless you know what you're doing.

    # Command to use for retrieving preserve_fqins value
    preserve_fqins_cmd: ./config_value.py DEFAULTS preserve_fqins config_defaults/defaults.ini config_custom/defaults.ini

    # Command to use for retrieving preserve_cnames value
    preserve_cnames_cmd: ./config_value.py DEFAULTS preserve_cnames config_defaults/defaults.ini config_custom/defaults.ini
